[2025-10-20T03:21:38.390+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gmm_segmentation.run_gmm manual__2025-10-20T03:21:36.507149+00:00 [queued]>
[2025-10-20T03:21:38.394+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gmm_segmentation.run_gmm manual__2025-10-20T03:21:36.507149+00:00 [queued]>
[2025-10-20T03:21:38.394+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T03:21:38.394+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-10-20T03:21:38.394+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T03:21:38.399+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_gmm> on 2025-10-20 03:21:36.507149+00:00
[2025-10-20T03:21:38.400+0000] {standard_task_runner.py:55} INFO - Started process 100 to run task
[2025-10-20T03:21:38.402+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gmm_segmentation', 'run_gmm', 'manual__2025-10-20T03:21:36.507149+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/gmm_segmentation.py', '--cfg-path', '/tmp/tmp1y656fnm']
[2025-10-20T03:21:38.402+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask run_gmm
[2025-10-20T03:21:38.424+0000] {task_command.py:388} INFO - Running <TaskInstance: gmm_segmentation.run_gmm manual__2025-10-20T03:21:36.507149+00:00 [running]> on host 1bd2eef1e1ab
[2025-10-20T03:21:38.449+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=asad_waraich
AIRFLOW_CTX_DAG_ID=gmm_segmentation
AIRFLOW_CTX_TASK_ID=run_gmm
AIRFLOW_CTX_EXECUTION_DATE=2025-10-20T03:21:36.507149+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-20T03:21:36.507149+00:00
[2025-10-20T03:21:38.471+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gmm_segmentation.py", line 23, in run_gmm_segmentation
    from sklearn.mixture import GaussianMixture
ModuleNotFoundError: No module named 'sklearn'
[2025-10-20T03:21:38.475+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gmm_segmentation, task_id=run_gmm, execution_date=20251020T032136, start_date=20251020T032138, end_date=20251020T032138
[2025-10-20T03:21:38.480+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 15 for task run_gmm (No module named 'sklearn'; 100)
[2025-10-20T03:21:38.503+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-20T03:21:38.513+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
