[2025-10-20T02:39:49.090+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gmm_segmentation_simple.run_gmm manual__2025-10-20T02:39:46.960735+00:00 [queued]>
[2025-10-20T02:39:49.094+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: gmm_segmentation_simple.run_gmm manual__2025-10-20T02:39:46.960735+00:00 [queued]>
[2025-10-20T02:39:49.095+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T02:39:49.095+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-10-20T02:39:49.095+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-20T02:39:49.101+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_gmm> on 2025-10-20 02:39:46.960735+00:00
[2025-10-20T02:39:49.104+0000] {standard_task_runner.py:55} INFO - Started process 80 to run task
[2025-10-20T02:39:49.106+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gmm_segmentation_simple', 'run_gmm', 'manual__2025-10-20T02:39:46.960735+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/gmm_segmentation.py', '--cfg-path', '/tmp/tmpqlbqlwxe']
[2025-10-20T02:39:49.106+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask run_gmm
[2025-10-20T02:39:49.130+0000] {task_command.py:388} INFO - Running <TaskInstance: gmm_segmentation_simple.run_gmm manual__2025-10-20T02:39:46.960735+00:00 [running]> on host 98595197e5ac
[2025-10-20T02:39:49.212+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=asad_waraich
AIRFLOW_CTX_DAG_ID=gmm_segmentation_simple
AIRFLOW_CTX_TASK_ID=run_gmm
AIRFLOW_CTX_EXECUTION_DATE=2025-10-20T02:39:46.960735+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-20T02:39:46.960735+00:00
[2025-10-20T02:39:49.215+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gmm_segmentation.py", line 21, in run_gmm_segmentation
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2025-10-20T02:39:49.226+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=gmm_segmentation_simple, task_id=run_gmm, execution_date=20251020T023946, start_date=20251020T023949, end_date=20251020T023949
[2025-10-20T02:39:49.274+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task run_gmm (No module named 'cv2'; 80)
[2025-10-20T02:39:49.286+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-20T02:39:49.297+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
